### PR TITLE
message->flight. Closes #2

### LINKED ISSUE #2: Terminology for data chunks
Do we need other terminology for data chunks?

Current terminology is in terms of “messages” (AKE units) and “frames”/”packets” (radio layer units). For good performance we want to minimize the number of radio layer units, the size of which are dependent on technology, regulations, configuration, etc.

The AKE is typically expected to be transported over CoAP which has its own fragmentation ("blocks"), but the AKE needs also to support other transport with analogous properties (see Section 2.1).

### PR DESCRIPTION
**Pull request by ekr**
I looked at issue #2 and I think it *is* confusing. As an example, you might think of the server's first flight g^y, [cert, sig...] as a single message or as two messages, one in the clear and one encrypted. And we might map them onto separate frames in some cases. 

This PR introduces flight and then changes message->flight where I think it's appropriate and then talks about wire/radio units where that's what we mean. There was one paragraph I had trouble with (marked in the text). Can someone explain what this means:

There are trade-offs between "few messages" and "few frames"; if overhead is spread out over more messages such that each message fits into a particular frame this may reduce the overall power consumption. While it may be possible to engineer such a solution for a particular radio technology and signature algorithm, the benefits in terms of fewer messages/round trips in general and for NB-IoT in particular (see {{nb-iot}}) are considered more important than optimizing for a specific scenario. Hence an optimal AKE protocol has 3 messages and each messages fits into as few frames as possible, ideally 1 frame per messages.

### CODE REVIEW

**Comment by ivajloip** [comment]
Hi @ekr ,

My reading of the paragraph in question during my review was that from the point of view of the AKE protocol we try to use as few flights/messages as possible and they should be as small as possible. Note that this might map to some extra L2 exchanges due to fragmentation compared to a case where one of the messages was made slightly bigger and another slightly smaller. Speaking in more concrete terms, imagine you have 2 messages of 60 bytes that need to be sent by one endpoint. If the L2 MTU is 50 bytes at that time, it might be better to split the messages to 40 and 80 bytes for example, given that you will need to use fragmentation for at least one of the messages anyway, but this way you might reduce the L2 messages from 4 to 3 as now one of the AKE protocol messages is not fragmented. If I understand it correctly, the draft is trying to say - we don't try to optimize at that level as it's really difficult.

**Comment by gselander** [comment]
The intent was exactly as @ivajloip explains. 

As I remember from the Secdispatch discussion, Rene Struik gave a specific example where SIGMA-R mapped to one L2 frame less than SIGMA-I. But this is not true in the general case. SIGMA-R typically gives more roundtrips than SIGMA-I. In particular when the AKE messages do fit into three L2 frames, SIGMA-R gives both more messages and more roundtrips/longer time to complete.

**Review by gselander — APPROVED** [review]
I'm fine with 76d7bc8. I think there are some more consequential changes following this shift in terminology, but I propose that we merge first and do those changes on the master branch.

**Comment by gselander** [comment]
I resolved the conflict with #15 and at the same time added back a statement about 3 flights as agreed with Karthik.

**Comment by gselander** [comment]
I also removed ekr's annotation since the comments above provides an explanation.

**Pull request merged**
